spring:
  application:
    name: e-commerce-admin-monolithic

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data/dummy-data.sql

  datasource:
    url: jdbc:mysql://localhost:13306/ecommerce_monolithic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info

server:
  port: 8081
